// Account protocol ids: 100-199.
export enum ProtocolAccount {
    AUTH_REQUEST = 101,
    AUTH_RESPONSE = 102,
    TOKEN_REFRESH = 103,
    CURRENT_ROOM_REQUEST = 104,
    CURRENT_ROOM_RESPONSE = 105,
    TOKEN_VERIFY_REQUEST = 106,
    TOKEN_VERIFY_RESPONSE = 107,
}
