from __future__ import annotations

import argparse
from pathlib import Path


PACKAGE_PROJECT_PS1 = '''# Generated by Plugins/DMToolBox/.codex/skills/ue-package-project/scripts/generate_package_scripts.py
param(
    [string]$ProjectPath = "",
    [string]$EngineRoot = "",
    [string]$Platform = "Win64",
    [string]$Configuration = "Development",
    [string]$ArchiveRoot = "",
    [switch]$PackageClient,
    [switch]$PackageServer,
    [switch]$Clean,
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Wait-BeforeExit {
    Write-Host ""
    Read-Host "Press Enter to exit"
}

function Stop-TranscriptSafe {
    try {
        Stop-Transcript | Out-Null
    }
    catch {
    }
}

function Write-Section {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message
    )

    Write-Host ""
    Write-Host "=== $Message ==="
}

function Resolve-FullPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PathValue
    )

    $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($PathValue)
}

function Get-ProjectFile {
    param(
        [string]$ExplicitProjectPath
    )

    if ($ExplicitProjectPath) {
        $ResolvedProjectPath = Resolve-FullPath -PathValue $ExplicitProjectPath
        if (-not (Test-Path -LiteralPath $ResolvedProjectPath)) {
            throw "Project file not found: $ResolvedProjectPath"
        }

        return Get-Item -LiteralPath $ResolvedProjectPath
    }

    $ProjectFiles = @(Get-ChildItem -LiteralPath $PSScriptRoot\\.. -Filter *.uproject -File)
    if ($ProjectFiles.Count -eq 0) {
        throw "No .uproject file found under $($PSScriptRoot)\\.. . Pass -ProjectPath explicitly."
    }

    if ($ProjectFiles.Count -gt 1) {
        throw "Multiple .uproject files found. Pass -ProjectPath explicitly."
    }

    return $ProjectFiles[0]
}

function Get-EngineRoot {
    param(
        [string]$ExplicitEngineRoot,
        [string]$ProjectDirectory
    )

    $CandidateRoots = @()
    $ProjectParentDirectory = Split-Path -Path $ProjectDirectory -Parent

    if ($ExplicitEngineRoot) {
        $CandidateRoots += $ExplicitEngineRoot
    }

    if ($env:UE_ENGINE_ROOT) {
        $CandidateRoots += $env:UE_ENGINE_ROOT
    }

    if ($env:UNREAL_ENGINE_ROOT) {
        $CandidateRoots += $env:UNREAL_ENGINE_ROOT
    }

    if ($ProjectParentDirectory) {
        $CandidateRoots += (Join-Path $ProjectParentDirectory "UnrealEngine")
    }

    foreach ($CandidateRoot in $CandidateRoots | Select-Object -Unique) {
        if (-not (Test-Path -LiteralPath $CandidateRoot)) {
            continue
        }

        $ResolvedCandidateRoot = Resolve-FullPath -PathValue $CandidateRoot
        $CurrentPath = $ResolvedCandidateRoot

        while ($CurrentPath) {
            $RunUATPath = Join-Path $CurrentPath "Engine\\Build\\BatchFiles\\RunUAT.bat"
            if (Test-Path -LiteralPath $RunUATPath) {
                return $CurrentPath
            }

            $ParentDirectory = Split-Path -Path $CurrentPath -Parent
            if (-not $ParentDirectory -or $ParentDirectory -eq $CurrentPath) {
                break
            }

            $CurrentPath = $ParentDirectory
        }
    }

    throw "Unable to locate Unreal Engine root. Pass -EngineRoot or set UE_ENGINE_ROOT."
}

function Invoke-UATBuildCookRun {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RunUATPath,
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,
        [Parameter(Mandatory = $true)]
        [string]$Label
    )

    Write-Host ""
    Write-Host ("Running UAT for {0}..." -f $Label)

    & $RunUATPath @Arguments
    $CommandExitCode = $LASTEXITCODE

    if ($CommandExitCode -ne 0) {
        throw "{0} packaging failed with exit code {1}" -f $Label, $CommandExitCode
    }
}

function New-ServerLaunchBat {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ServerArchiveDirectory,
        [Parameter(Mandatory = $true)]
        [string]$ProjectName
    )

    $ServerPlatformDirectory = Join-Path $ServerArchiveDirectory "WindowsServer"
    $ServerRootDirectory = Join-Path $ServerPlatformDirectory $ProjectName
    $ServerBinaryDirectory = Join-Path $ServerRootDirectory "Binaries\\Win64"
    $LaunchBatPath = Join-Path $ServerPlatformDirectory "RunServerWithLog.bat"
    $ServerExeName = "{0}Server.exe" -f $ProjectName

    if (-not (Test-Path -LiteralPath $ServerBinaryDirectory)) {
        throw "Server binary directory not found after packaging: $ServerBinaryDirectory"
    }

    $BatLines = @(
        "@echo off",
        "setlocal",
        "",
        ('cd /d "%~dp0{0}\\Binaries\\Win64"' -f $ProjectName),
        ('start "" "{0}" /Game/NoOutsiders/Levels/L_Gameplay -log -port=7777' -f $ServerExeName),
        "",
        "endlocal & exit /b 0"
    )

    Set-Content -LiteralPath $LaunchBatPath -Value $BatLines -Encoding ASCII
    Write-Host ("Created server launch script: {0}" -f $LaunchBatPath)
}

$ExitCode = 0
$TranscriptStarted = $false

Write-Section -Message "PackageProject Startup"
Write-Host "Script Path  : $PSCommandPath"
Write-Host "Script Root  : $PSScriptRoot"
Write-Host "ProjectPath  : $ProjectPath"
Write-Host "EngineRoot   : $EngineRoot"
Write-Host "Platform     : $Platform"
Write-Host "Config       : $Configuration"
Write-Host "PackageClient: $PackageClient"
Write-Host "PackageServer: $PackageServer"

try {
    $ProjectFile = Get-ProjectFile -ExplicitProjectPath $ProjectPath
    $ResolvedProjectPath = $ProjectFile.FullName
    $ProjectName = [System.IO.Path]::GetFileNameWithoutExtension($ProjectFile.Name)
    $ProjectDir = $ProjectFile.Directory.FullName

    $LogsDirectory = Join-Path $ProjectDir "Saved\\Logs"
    New-Item -ItemType Directory -Force -Path $LogsDirectory | Out-Null

    $LogTimestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $LogFilePath = Join-Path $LogsDirectory ("PackageProject_{0}.log" -f $LogTimestamp)
    Start-Transcript -Path $LogFilePath -Force | Out-Null
    $TranscriptStarted = $true

    $ResolvedEngineRoot = Get-EngineRoot -ExplicitEngineRoot $EngineRoot -ProjectDirectory $ProjectDir
    $RunUATPath = Join-Path $ResolvedEngineRoot "Engine\\Build\\BatchFiles\\RunUAT.bat"

    if (-not $PackageClient.IsPresent -and -not $PackageServer.IsPresent) {
        $PackageClient = $true
    }

    if (-not $ArchiveRoot) {
        $ArchiveRoot = Join-Path $ProjectDir "PackageBuilds"
    }

    $ResolvedArchiveRoot = Resolve-FullPath -PathValue $ArchiveRoot
    New-Item -ItemType Directory -Force -Path $ResolvedArchiveRoot | Out-Null

    $Timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $ArchiveDirectoryName = "{0}_Ver_{1}" -f $ProjectName, $Timestamp
    $ArchiveDirectory = Join-Path $ResolvedArchiveRoot $ArchiveDirectoryName

    if (Test-Path -LiteralPath $ArchiveDirectory) {
        throw "Archive output already exists: $ArchiveDirectory"
    }

    New-Item -ItemType Directory -Force -Path $ArchiveDirectory | Out-Null

    Write-Host "Project      : $ResolvedProjectPath"
    Write-Host "Engine Root  : $ResolvedEngineRoot"
    Write-Host "Platform     : $Platform"
    Write-Host "Configuration: $Configuration"
    Write-Host "Output       : $ArchiveDirectory"
    Write-Host "Log File     : $LogFilePath"
    Write-Host "Targets      : $(
        @(
            if ($PackageClient) { "Client" }
            if ($PackageServer) { "Server" }
        ) -join ', '
    )"

    $CommonArguments = @(
        "BuildCookRun",
        "-project=$ResolvedProjectPath",
        "-build",
        "-cook",
        "-stage",
        "-pak",
        "-archive",
        "-utf8output"
    )

    if ($Clean.IsPresent) {
        $CommonArguments += "-clean"
    }

    if ($SkipBuild.IsPresent) {
        $CommonArguments = $CommonArguments | Where-Object { $_ -ne "-build" }
    }

    if ($PackageClient) {
        $ClientArchiveDirectory = Join-Path $ArchiveDirectory "Client"
        New-Item -ItemType Directory -Force -Path $ClientArchiveDirectory | Out-Null

        $ClientArguments = @(
            $CommonArguments +
            @(
                "-platform=$Platform",
                "-clientconfig=$Configuration",
                "-archivedirectory=$ClientArchiveDirectory",
                "-prereqs"
            )
        )

        Invoke-UATBuildCookRun -RunUATPath $RunUATPath -Arguments $ClientArguments -Label "Client"
    }

    if ($PackageServer) {
        $ServerArchiveDirectory = Join-Path $ArchiveDirectory "Server"
        New-Item -ItemType Directory -Force -Path $ServerArchiveDirectory | Out-Null

        $ServerArguments = @(
            $CommonArguments +
            @(
                "-server",
                "-noclient",
                "-serverplatform=$Platform",
                "-serverconfig=$Configuration",
                "-archivedirectory=$ServerArchiveDirectory"
            )
        )

        Invoke-UATBuildCookRun -RunUATPath $RunUATPath -Arguments $ServerArguments -Label "Server"
        New-ServerLaunchBat -ServerArchiveDirectory $ServerArchiveDirectory -ProjectName $ProjectName
    }

    Write-Host ""
    Write-Host "Packaging completed successfully."
    Write-Host "Archive directory: $ArchiveDirectory"
}
catch {
    if ($ExitCode -eq 0) {
        $ExitCode = 1
    }

    Write-Section -Message "Packaging Failed"
    Write-Host ("Error Type   : {0}" -f $_.Exception.GetType().FullName)
    Write-Host ("Error Message: {0}" -f $_.Exception.Message)

    if ($_.InvocationInfo) {
        Write-Host ("At Script    : {0}" -f $_.InvocationInfo.PositionMessage.Trim())
    }

    if ($TranscriptStarted) {
        Write-Host ("Log File     : {0}" -f $LogFilePath)
    }
}
finally {
    if ($TranscriptStarted) {
        Stop-TranscriptSafe
    }

    Wait-BeforeExit
}

exit $ExitCode
'''


BAT_TEMPLATE = '''@echo off
setlocal

powershell.exe -ExecutionPolicy Bypass -File "%~dp0PackageProject.ps1"{arguments}
set "EXIT_CODE=%ERRORLEVEL%"

endlocal & exit /b %EXIT_CODE%
'''


def find_project_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if any(candidate.glob("*.uproject")):
            return candidate
    raise FileNotFoundError(f"Unable to locate a .uproject above {start}")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii", newline="\r\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate project packaging scripts into Scripts/.")
    parser.add_argument("--project-root", type=Path, help="Project root containing the .uproject")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    project_root = args.project_root.resolve() if args.project_root else find_project_root(script_dir)
    scripts_dir = project_root / "Scripts"

    write_text(scripts_dir / "PackageProject.ps1", PACKAGE_PROJECT_PS1)
    write_text(scripts_dir / "PackageClient.bat", BAT_TEMPLATE.format(arguments=" -PackageClient"))
    write_text(scripts_dir / "PackageServer.bat", BAT_TEMPLATE.format(arguments=" -PackageServer"))
    write_text(
        scripts_dir / "PackageClientAndServer.bat",
        BAT_TEMPLATE.format(arguments=" -PackageClient -PackageServer"),
    )

    print(f"Generated packaging scripts in {scripts_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
